# Generated by Django 4.0.3 on 2022-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField()),
                ('close_chg', models.FloatField()),
                ('sell', models.IntegerField()),
            ],
            options={
                'db_table': 'detect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_date', models.DateField(primary_key=True, serialize=False)),
                ('hpr_percent', models.FloatField()),
                ('mdd', models.FloatField(db_column='MDD')),
                ('buy_hold_hpr_percent', models.FloatField()),
                ('buy_hold_mdd', models.FloatField(db_column='buy_hold_MDD')),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
    ]
