# Generated by Django 4.0.3 on 2022-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('crawling_date', models.DateField(primary_key=True, serialize=False)),
                ('n_count', models.SmallIntegerField()),
                ('p_count', models.SmallIntegerField()),
                ('neu_count', models.SmallIntegerField()),
                ('k_val', models.FloatField()),
            ],
            options={
                'db_table': 'sentiment',
                'managed': False,
            },
        ),
    ]
