# Generated by Django 4.0.3 on 2022-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordcloudTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'wordcloud_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Topten',
        ),
    ]
